import Link from "next/link";
import { SITE } from "@/lib/site";
import "./hero-workshop.css";

/**
 * The hero's figure: the workshop, a printer and a robot arm working together,
 * as a story told on a 14s loop (hero-workshop.css):
 *
 *   1. The printer prints a robot, fast: the gantry climbs a layer at a time
 *      and the hotend races across each one, as wide as the robot is at that
 *      height; the layer just laid glows gold and cools.
 *   2. The head parks out of the way; the robot wakes, eyes then antenna, and
 *      walks to the edge of the bed.
 *   3. The arm reaches in, takes it by the antenna, lifts it out over the top
 *      and sets it down on the floor. That is the arm's job: it unloads the
 *      printer, as arms do on real print farms.
 *   4. The robot hops, waves; the arm claps its jaws back and goes home; the
 *      robot walks off; the printer homes for the next one.
 *
 * It is CSS on SVG: no script, nothing to hydrate. The hotend's passes, the
 * arm's joint angles (solved from where the gripper has to be) and the robot's
 * swing as it hangs are generated by scripts/hero-workshop-keyframes.mjs, and
 * the geometry here must match that script. Under prefers-reduced-motion the
 * finished robot stands on the bed, awake, and the arm waits beside it.
 *
 * The robot is drawn once about its own origin (feet at 0, centre at 0) and
 * placed by a transform attribute; CSS transforms go on wrappers that carry
 * none, because a CSS transform replaces an element's transform attribute
 * rather than composing with it.
 *
 * The printer and the arm are doors: the printer opens the print service, the
 * arm the actuators aisle. Because the drawing holds links it is role="group",
 * not role="img", which would hide them from assistive tech.
 */

/** Where the robot stands while it is printed, and its scale. */
const RX = 210;
const BED = 410;
const S = 0.78;
/** How tall the robot is: the distance the gantry climbs. */
const H = 158 * S;
/** The arm: shoulder, elbow and wrist as drawn, all straight up; CSS bends them. */
const SH = { x: 468, y: 430 };
const EL = { x: 468, y: 300 };
const WR = { x: 468, y: 170 };

function Door({
  href,
  label,
  external = false,
  hit,
  tip,
  children,
}: {
  href: string;
  label: string;
  external?: boolean;
  hit: [number, number, number, number];
  tip: [number, number];
  children: React.ReactNode;
}) {
  const text = label.toUpperCase();
  const w = text.length * 6.1 + 13;
  const inner = (
    <>
      <rect className="vc-hit" x={hit[0]} y={hit[1]} width={hit[2]} height={hit[3]} rx="6" />
      <g className="vc-part-body">{children}</g>
      <g className="vc-tip">
        <rect x={tip[0] - w / 2} y={tip[1] - 10.5} width={w} height="15" rx="3" fill="var(--vc-ink)" />
        <text
          x={tip[0]}
          y={tip[1]}
          textAnchor="middle"
          fill="var(--vc-ground)"
          fontFamily="var(--font-mono)"
          fontSize="8.6"
          letterSpacing="0.9"
        >
          {text}
        </text>
      </g>
    </>
  );
  return external ? (
    <a href={href} target="_blank" rel="noreferrer" className="vc-part" aria-label={label}>
      {inner}
    </a>
  ) : (
    <Link href={href} className="vc-part" aria-label={label}>
      {inner}
    </Link>
  );
}

/**
 * The robot's silhouette about its own origin: clips its layer lines and its
 * glow. The arm it waves with carries its own lines, so it is left out of the
 * one for the body.
 */
function RobotSilhouette({ waveArm = true }: { waveArm?: boolean }) {
  return (
    <>
      <circle cx="0" cy="-152" r="6" />
      <rect x="-2" y="-147" width="4" height="14" />
      <rect x="-38" y="-134" width="76" height="52" rx="12" />
      <rect x="-45" y="-118" width="8" height="20" rx="3" />
      <rect x="37" y="-118" width="8" height="20" rx="3" />
      <rect x="-12" y="-82" width="24" height="8" />
      <rect x="-50" y="-75" width="100" height="58" rx="9" />
      <rect x="-66" y="-70" width="16" height="40" rx="8" />
      {waveArm ? <rect x="50" y="-70" width="16" height="40" rx="8" /> : null}
      <rect x="-30" y="-18" width="18" height="13" />
      <rect x="12" y="-18" width="18" height="13" />
      <rect x="-35" y="-6" width="28" height="6" rx="2" />
      <rect x="7" y="-6" width="28" height="6" rx="2" />
    </>
  );
}

/** The robot as drawn: body, layer lines, face, the bolt on its chest. */
function Robot() {
  const part = { fill: "var(--vc-raised)", stroke: "var(--vc-muted)", strokeWidth: 1.7 } as const;
  return (
    <>
      <ellipse className="vc-bot-shadow" cx="0" cy="1" rx="46" ry="3.5" fill="var(--vc-ink)" opacity="0.1" />
      <g {...part}>
        <rect x="-2" y="-147" width="4" height="14" />
        <rect x="-45" y="-118" width="8" height="20" rx="3" />
        <rect x="37" y="-118" width="8" height="20" rx="3" />
        <rect x="-38" y="-134" width="76" height="52" rx="12" />
        <rect x="-12" y="-82" width="24" height="8" />
        <rect x="-66" y="-70" width="16" height="40" rx="8" />
        <rect x="-50" y="-75" width="100" height="58" rx="9" />
        <g className="vc-bot-leg-l">
          <rect x="-30" y="-18" width="18" height="13" />
          <rect x="-35" y="-6" width="28" height="6" rx="2" />
        </g>
        <g className="vc-bot-leg-r">
          <rect x="12" y="-18" width="18" height="13" />
          <rect x="7" y="-6" width="28" height="6" rx="2" />
        </g>
      </g>
      {/* layer lines: what makes a print read as printed */}
      <rect x="-70" y="-160" width="140" height="160" fill="url(#vc-layers)" clipPath="url(#vc-robot-clip-body)" />
      {/* the arm it waves with, apart so it can swing from the shoulder */}
      <g className="vc-bot-wave">
        <rect x="50" y="-70" width="16" height="40" rx="8" {...part} />
        <rect x="50" y="-70" width="16" height="40" rx="8" fill="url(#vc-layers)" />
      </g>
      {/* bolts at the shoulders and ears */}
      <g fill="var(--vc-muted)">
        <circle cx="-41" cy="-108" r="1.6" />
        <circle cx="41" cy="-108" r="1.6" />
        <circle cx="-42" cy="-67" r="1.6" />
        <circle cx="42" cy="-67" r="1.6" />
      </g>
      {/* the face: a visor with two eyes and a smile */}
      <rect x="-28" y="-125" width="56" height="34" rx="9" fill="var(--vc-sheet)" stroke="var(--vc-muted)" strokeWidth="1.4" />
      <circle className="vc-bot-eye" cx="-13" cy="-110" r="6.5" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.4" />
      <circle className="vc-bot-eye" cx="13" cy="-110" r="6.5" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.4" />
      <path d="M-8 -99q8 5 16 0" fill="none" stroke="var(--vc-muted)" strokeWidth="1.5" strokeLinecap="round" />
      {/* the chest: a panel, the bolt, two dials */}
      <rect x="-24" y="-66" width="48" height="36" rx="5" fill="var(--vc-sheet)" stroke="var(--vc-muted)" strokeWidth="1.4" />
      <path d="M4 -61l-11 14h9l-4 11 12-15h-9z" fill="var(--vc-gold)" />
      <circle cx="-36" cy="-30" r="3" fill="none" stroke="var(--vc-muted)" strokeWidth="1.2" />
      <circle cx="36" cy="-30" r="3" fill="none" stroke="var(--vc-muted)" strokeWidth="1.2" />
      <circle className="vc-bot-led" cx="0" cy="-152" r="6" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.5" />
      {/* the spark as it powers up */}
      <path
        className="vc-bot-spark"
        d="M-11 -162l-9-6M11 -162l9-6M0 -164v-10M-13 -150h-9M13 -150h9"
        stroke="var(--vc-gold)"
        strokeWidth="2.6"
        strokeLinecap="round"
      />
    </>
  );
}

/** The arm's joints, nested so each bends from the one before it; `children` rides on the wrist. */
function ArmJoints({ upper, fore, children }: { upper?: React.ReactNode; fore?: React.ReactNode; children: React.ReactNode }) {
  return (
    <g className="vc-arm-shoulder">
      {upper}
      <g className="vc-arm-elbow">
        {fore}
        <g className="vc-arm-wrist">{children}</g>
      </g>
    </g>
  );
}

export function HeroWorkshop({ className = "max-w-[500px]" }: { className?: string }) {
  const ink = { fill: "var(--vc-sheet)", stroke: "var(--vc-muted)", strokeWidth: 1.8 } as const;
  const raised = { fill: "var(--vc-raised)", stroke: "var(--vc-muted)", strokeWidth: 1.6 } as const;
  const line = { fill: "none", stroke: "var(--vc-line)", strokeWidth: 1.2 } as const;
  const digits = Array.from({ length: 11 }, (_, i) => `${i * 10}%`);

  return (
    <div className={`mx-auto w-full ${className}`}>
      <svg
        viewBox="0 0 700 560"
        className="vc-workshop w-full"
        role="group"
        aria-label="A 3D printer prints a small robot; a robotic arm lifts it out and sets it down, and it waves and walks off"
      >
        <defs>
          <pattern id="vc-layers" patternUnits="userSpaceOnUse" width="8" height="5">
            <path d="M0 4.5H8" stroke="var(--vc-trace)" strokeWidth="1" />
          </pattern>
          <pattern id="vc-heatbed" patternUnits="userSpaceOnUse" width="6" height="6">
            <path d="M-1 7L7-1" stroke="var(--vc-trace)" strokeWidth="0.85" fill="none" />
          </pattern>
          <pattern id="vc-pei" patternUnits="userSpaceOnUse" width="7" height="4">
            <circle cx="2" cy="2" r="0.7" fill="var(--vc-trace)" />
          </pattern>
          <clipPath id="vc-robot-clip-body">
            <RobotSilhouette waveArm={false} />
          </clipPath>
          {/* the silhouette where it is printed, for the fresh-layer glow */}
          <clipPath id="vc-robot-clip-bed">
            <g transform={`translate(${RX} ${BED}) scale(${S})`}>
              <RobotSilhouette />
            </g>
          </clipPath>
          <clipPath id="vc-digits">
            <rect x="140" y="455" width="34" height="14" />
          </clipPath>
          {/* the layer just laid is hot: gold at the top edge, cooling below */}
          <linearGradient id="vc-hot" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0" stopColor="var(--vc-gold)" stopOpacity="1" />
            <stop offset="0.2" stopColor="var(--vc-gold)" stopOpacity="0.85" />
            <stop offset="1" stopColor="var(--vc-gold)" stopOpacity="0" />
          </linearGradient>
        </defs>

        {/* registration ticks, as on a drawing sheet */}
        <g stroke="var(--vc-line)" strokeWidth="1.5" fill="none">
          <path d="M4 22V4h18M678 4h18v18M696 538v18h-18M22 556H4v-18" />
        </g>

        {/* shadows that ground the machines on the floor */}
        <ellipse cx="210" cy="490" rx="188" ry="6" fill="var(--vc-ink)" opacity="0.07" />
        <ellipse cx="468" cy="490" rx="62" ry="5" fill="var(--vc-ink)" opacity="0.08" />

        {/* ------------------------------------------------------- printer */}
        <Door href={SITE.printingUrl} external label="3D printing" hit={[34, 6, 352, 490]} tip={[210, 516]}>
          {/* the spool on its holder, the filament into the extruder */}
          <path d="M300 70V48" stroke="var(--vc-muted)" strokeWidth="2.4" />
          <g className="vc-spool">
            <circle cx="300" cy="38" r="28" {...ink} />
            <circle cx="300" cy="38" r="21.5" fill="none" stroke="var(--vc-gold)" strokeWidth="9" opacity="0.9" />
            <circle cx="300" cy="38" r="24" fill="none" stroke="var(--vc-sheet)" strokeWidth="0.8" opacity="0.7" />
            <circle cx="300" cy="38" r="20" fill="none" stroke="var(--vc-sheet)" strokeWidth="0.8" opacity="0.7" />
            <circle cx="300" cy="38" r="9" {...raised} />
            <path d="M300 22v6M316 38h-6M300 54v-6M284 38h6" stroke="var(--vc-muted)" strokeWidth="1.3" />
            <circle cx="300" cy="38" r="2.4" fill="var(--vc-muted)" />
          </g>
          <path d="M279 50C270 54 266 58 262 62" fill="none" stroke="var(--vc-gold)" strokeWidth="2" />
          <rect x="234" y="54" width="28" height="18" rx="3" {...raised} />
          <circle cx="248" cy="63" r="4.5" fill="var(--vc-sheet)" stroke="var(--vc-muted)" strokeWidth="1.2" />

          {/* the build chamber: the back plate the reveal panel matches */}
          <rect x="72" y="92" width="276" height="350" fill="var(--vc-sheet)" />
          <path d="M84 104h14M84 104v14M336 104h-14M336 104v14" {...line} />

          {/* the frame: two extrusions with their slots, the top bar */}
          <rect x="52" y="80" width="20" height="366" rx="3" {...ink} />
          <rect x="348" y="80" width="20" height="366" rx="3" {...ink} />
          <path d="M58.5 98V430M65.5 98V430M354.5 98V430M361.5 98V430" {...line} />
          <rect x="46" y="70" width="328" height="22" rx="4" {...ink} />
          <text x="64" y="85" fill="var(--vc-muted)" fontFamily="var(--font-mono)" fontSize="10" letterSpacing="2.4">
            VOLTCRAFT
          </text>
          <circle className="vc-print-status" cx="356" cy="81" r="3.5" fill="var(--vc-gold)" />

          {/* lead screws down to their motors, with couplers */}
          <g stroke="var(--vc-muted)" fill="none">
            <path d="M86 100V428M334 100V428" strokeWidth="1.2" />
            <path d="M86 100V428M334 100V428" strokeWidth="4" strokeDasharray="1.2 3" opacity="0.55" />
          </g>
          <rect x="81" y="92" width="10" height="9" rx="1.5" {...raised} />
          <rect x="329" y="92" width="10" height="9" rx="1.5" {...raised} />
          <rect x="77" y="426" width="18" height="16" rx="2" {...raised} />
          <rect x="325" y="426" width="18" height="16" rx="2" {...raised} />

          {/* the bed: textured plate, the heater under it, clips, the supports */}
          <rect x="116" y="428" width="10" height="14" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.2" />
          <rect x="294" y="428" width="10" height="14" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.2" />
          <rect x="104" y="420" width="212" height="8" fill="url(#vc-heatbed)" stroke="var(--vc-line)" strokeWidth="1" />
          <rect x="96" y={BED} width="228" height="10" rx="2" {...ink} />
          <rect x="99" y={BED + 2} width="222" height="6" fill="url(#vc-pei)" />
          <path d={`M100 ${BED - 3}h12M308 ${BED - 3}h12`} stroke="var(--vc-muted)" strokeWidth="2.4" />

          {/* base: the screen with the job's progress, the dial, the vents, feet */}
          <rect x="56" y="482" width="26" height="8" rx="2" fill="var(--vc-muted)" opacity="0.8" />
          <rect x="338" y="482" width="26" height="8" rx="2" fill="var(--vc-muted)" opacity="0.8" />
          <rect x="40" y="442" width="340" height="42" rx="7" {...ink} />
          <rect x="60" y="451" width="118" height="24" rx="3" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.4" />
          <rect x="68" y="460" width="66" height="6" rx="3" fill="var(--vc-line)" opacity="0.5" />
          <rect className="vc-print-progress" x="68" y="460" width="66" height="6" rx="3" fill="var(--vc-gold)" />
          <g clipPath="url(#vc-digits)">
            <g className="vc-print-digits" fill="var(--vc-muted)" fontFamily="var(--font-mono)" fontSize="9" textAnchor="end">
              {digits.map((d, i) => (
                <text key={d} x="172" y={466 + i * 14}>
                  {d}
                </text>
              ))}
            </g>
          </g>
          <circle cx="204" cy="463" r="10" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.5" />
          <circle cx="204" cy="463" r="3.2" fill="var(--vc-muted)" />
          <path d="M204 453.5v3" stroke="var(--vc-muted)" strokeWidth="1.4" />
          <path d="M290 452v22M300 452v22M310 452v22M320 452v22M330 452v22M340 452v22M350 452v22M360 452v22" {...line} />
        </Door>

        {/* ----------------------------------------------------------- arm */}
        <Door href="/shop/actuators" label="Actuators" hit={[396, 150, 150, 340]} tip={[468, 516]}>
          <rect x="420" y="474" width="96" height="16" rx="4" {...ink} />
          <circle cx="432" cy="482" r="2.6" fill="var(--vc-muted)" />
          <circle cx="504" cy="482" r="2.6" fill="var(--vc-muted)" />
          <path d="M440 474L448 446H488L496 474Z" {...raised} strokeLinejoin="round" />
          <path d="M452 458H484" {...line} />
          <ArmJoints
            upper={
              <>
                <rect x={SH.x - 13} y={EL.y - 4} width="26" height={SH.y - EL.y + 8} rx="13" {...ink} />
                <path d={`M${SH.x + 9} ${SH.y - 14}C${SH.x + 18} 390 ${SH.x + 18} 340 ${SH.x + 9} ${EL.y + 10}`} stroke="var(--vc-trace)" strokeWidth="1.6" fill="none" />
                <rect x={SH.x - 13} y="362" width="26" height="7" fill="var(--vc-gold)" opacity="0.85" />
              </>
            }
            fore={
              <>
                <rect x={EL.x - 9} y={WR.y - 4} width="18" height={EL.y - WR.y + 8} rx="9" {...ink} />
                <path d={`M${EL.x + 6} ${EL.y - 12}C${EL.x + 13} 260 ${EL.x + 13} 210 ${EL.x + 6} ${WR.y + 10}`} stroke="var(--vc-trace)" strokeWidth="1.5" fill="none" />
                <circle cx={EL.x} cy={EL.y} r="16" {...raised} strokeWidth={1.8} />
                <circle cx={EL.x} cy={EL.y} r="6" fill="var(--vc-gold)" />
              </>
            }
          >
            {/* the gripper's palm, hanging under the wrist */}
            <rect x={WR.x - 14} y={WR.y + 6} width="28" height="14" rx="4" {...raised} />
            <circle cx={WR.x} cy={WR.y} r="10" {...raised} />
            <circle cx={WR.x} cy={WR.y} r="3.5" fill="var(--vc-gold)" />
          </ArmJoints>
          {/* the shoulder, over the root of the arm */}
          <circle cx={SH.x} cy={SH.y} r="22" {...raised} strokeWidth={1.8} />
          <circle cx={SH.x} cy={SH.y} r="8" fill="var(--vc-gold)" />
          <path d={`M${SH.x} ${SH.y - 15}v-3M${SH.x + 15} ${SH.y}h3M${SH.x - 15} ${SH.y}h-3`} stroke="var(--vc-muted)" strokeWidth="1.5" />
        </Door>

        {/* the robot, drawn over the machines so it can be carried in front of
            them; then the panel that hides what is not printed yet, lifting
            from the bed up as the layers go down; then the gantry over both */}
        <g className="vc-bot">
          <g transform={`translate(${RX} ${BED}) scale(${S})`}>
            <Robot />
          </g>
        </g>
        <rect className="vc-print-cover" x={RX - 58} y={BED - H - 4} width="116" height={H + 4} fill="var(--vc-sheet)" />
        <g clipPath="url(#vc-robot-clip-bed)">
          <g className="vc-print-heat">
            <rect x={RX - 60} y={BED} width="120" height="20" fill="url(#vc-hot)" />
            <rect x={RX - 60} y={BED} width="120" height="2.5" fill="var(--vc-gold)" />
          </g>
        </g>

        {/* the gantry: it climbs with the print, the hotend races on its belt */}
        <g className="vc-print-gantry">
          <rect x="46" y="344" width="32" height="38" rx="4" {...raised} />
          <rect x="342" y="344" width="32" height="38" rx="4" {...raised} />
          <path d="M78 352H342M78 361H342" stroke="var(--vc-muted)" strokeWidth="2" />
          <path className="vc-print-belt" d="M78 374H342" stroke="var(--vc-muted)" strokeWidth="2.4" strokeDasharray="3 3" />
          <circle cx="62" cy="374" r="5" {...raised} />
          <circle cx="358" cy="374" r="5" {...raised} />
          <g className="vc-print-x">
            <rect x={RX - 23} y="340" width="46" height="40" rx="5" fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.7" />
            <circle cx={RX} cy="358" r="12" fill="var(--vc-sheet)" stroke="var(--vc-muted)" strokeWidth="1.4" />
            <g className="vc-print-fan">
              <path d={`M${RX} 358l0-9M${RX} 358l8 5M${RX} 358l-8 5`} stroke="var(--vc-muted)" strokeWidth="2" strokeLinecap="round" />
            </g>
            <circle cx={RX} cy="358" r="2.2" fill="var(--vc-muted)" />
            {/* the part-cooling duct, aimed at the nozzle */}
            <path d={`M${RX + 23} 368h6l-4 22h-6`} fill="var(--vc-raised)" stroke="var(--vc-muted)" strokeWidth="1.3" strokeLinejoin="round" />
            <rect x={RX - 11} y="380" width="22" height="14" rx="2" fill="var(--vc-sheet)" stroke="var(--vc-muted)" strokeWidth="1.5" />
            <rect className="vc-heater" x={RX - 11} y="380" width="22" height="14" rx="2" fill="var(--vc-gold)" />
            <path d={`M${RX - 9} 385h18M${RX - 9} 389h18`} stroke="var(--vc-line)" strokeWidth="1" />
            <path d={`M${RX - 6} 394h12l-6 ${BED - 394}z`} fill="var(--vc-muted)" />
            <circle className="vc-nozzle-glow" cx={RX} cy={BED - 1} r="5" fill="var(--vc-gold)" />
          </g>
        </g>

        {/* the gripper's fingers again, in front of the robot it holds */}
        <g className="vc-arm-front">
          <ArmJoints>
            <g className="vc-jaw vc-jaw-a">
              <path d={`M${WR.x - 9} ${WR.y + 19}h6l2 19h-5z`} {...raised} strokeWidth={1.4} strokeLinejoin="round" />
            </g>
            <g className="vc-jaw vc-jaw-b">
              <path d={`M${WR.x + 3} ${WR.y + 19}h6l-3 19h-5z`} {...raised} strokeWidth={1.4} strokeLinejoin="round" />
            </g>
          </ArmJoints>
        </g>

        {/* the dust it raises, set down on the floor */}
        <g className="vc-ws-dust" fill="var(--vc-line)">
          <circle cx="556" cy="489" r="4" />
          <circle cx="544" cy="485" r="3" />
          <circle cx="644" cy="489" r="4" />
          <circle cx="656" cy="485" r="3" />
        </g>

        {/* the floor line and a dimension line, because the sheet always carries one */}
        <path d="M24 490H676" stroke="var(--vc-line)" strokeWidth="1.2" />
        <g stroke="var(--vc-faint)" strokeWidth="1.1">
          <path d="M40 538h620M40 532v12M660 532v12" />
        </g>
      </svg>
    </div>
  );
}
